import React from 'react';
import PerfectScrollbar from '../../src/index';

/* eslint-disable max-len */
export default () => (
  <PerfectScrollbar>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed erat ante, egestas quis vehicula vel, pretium vitae massa. Ut sed pulvinar tellus. Aliquam ex elit, auctor et facilisis ut, pellentesque id risus. Quisque ex quam, dictum a aliquet vitae, viverra ac nisi. Nunc cursus mauris et massa posuere sodales. Pellentesque feugiat nunc at velit dignissim, in aliquet velit luctus. Praesent dignissim odio non vestibulum fermentum. Duis in erat non tortor malesuada venenatis. Nam vel massa orci. Sed feugiat at libero ut interdum. Sed non efficitur quam, in eleifend est. Mauris at dolor viverra, cursus nulla quis, scelerisque est. Sed consequat nulla sit amet mauris volutpat, sit amet tristique orci varius. Vivamus ipsum arcu, pulvinar quis pellentesque nec, scelerisque at neque. Nam diam ex, volutpat at neque id, commodo tempus quam.</p>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras tincidunt sapien in tellus rutrum, a porttitor ante dapibus. Sed blandit lacus ligula, nec aliquet turpis vehicula vitae. Nunc aliquam eu eros sed placerat. Phasellus cursus dapibus enim quis commodo. Cras in justo eleifend odio pellentesque auctor. Aenean consequat lectus nec porttitor consectetur. Etiam ipsum ante, imperdiet id dictum id, fermentum varius metus. Cras vel ex gravida, porttitor velit eget, laoreet sapien. Morbi vitae turpis eget orci tempus posuere a sed ligula. Sed elementum tincidunt ipsum et ultricies. Pellentesque ornare lectus eu felis fringilla interdum.</p>
    <p>Pellentesque nec cursus ligula. Curabitur lectus eros, cursus vitae dapibus eu, maximus vitae tortor. Sed a mauris neque. Nullam quis felis nulla. Nunc interdum ligula vitae turpis suscipit, eu vestibulum tellus fringilla. Nullam pulvinar accumsan neque eget elementum. Nullam dapibus volutpat sapien, sed vulputate nisi finibus egestas. Sed ac erat iaculis, pretium nibh at, tempus dui. Fusce aliquam ultricies mollis. Quisque consectetur massa libero, eget placerat dui euismod ac. Nunc nec purus a sem semper rhoncus. Pellentesque ut mollis dui. Nam maximus libero nec quam pretium, vel commodo lorem dictum. Aliquam non arcu vulputate, faucibus nunc sed, suscipit magna. Fusce at vulputate dui, vehicula venenatis quam.</p>
    <p>Nulla facilisi. Sed finibus gravida fringilla. Aenean non odio eu tellus congue rhoncus. Donec at quam imperdiet justo venenatis sollicitudin. Sed suscipit consequat bibendum. Nullam semper imperdiet rutrum. Mauris ornare, nibh sit amet pretium sollicitudin, velit eros facilisis lectus, non dignissim mi lorem a orci. Maecenas dapibus mollis tincidunt.</p>
    <p>In sit amet tincidunt lorem. In mattis urna nibh, in cursus dolor iaculis nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam auctor convallis felis quis dignissim. Quisque eu placerat arcu. Morbi nunc nulla, condimentum pulvinar rhoncus sed, dapibus a risus. Integer eleifend mi nec dui egestas placerat. Curabitur finibus fringilla ultricies. Suspendisse euismod, risus eget condimentum vulputate, nulla dui sollicitudin eros, sit amet hendrerit velit purus in libero. Donec quis tortor sagittis tellus pulvinar vehicula in eu lacus. Sed tincidunt scelerisque erat id viverra. Donec lacus felis, suscipit et risus vel, laoreet consectetur odio. Sed a pharetra odio.</p>
  </PerfectScrollbar>
);
